### Simple Email
POST http://localhost:8081/email/simple
Content-Type: application/json

### Simple Email using a template
POST http://localhost:8081/email/simpletemplate
Content-Type: application/json

### Simple Email with an attachment
POST http://localhost:8081/email/simpleattachment
Content-Type: application/json

### HTML Email with an attachment
POST http://localhost:8081/email/htmlattachment
Content-Type: application/json