### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8081/comments/documents/9
Content-Type: application/json

###
POST http://localhost:8081/comments
Content-Type: application/json

{
  "documentId": "4",
  "body": "comment body 1",
  "creator": "1",
  "parentCommentId": "1"
}

###
PUT http://localhost:8081/comments/12
Content-Type: application/json

{
  "body": "edited comment body 1"
}


###
DELETE http://localhost:8081/comments/10
Content-Type: application/json

